from PyQt6 import QtCore, QtGui, QtWidgets
from signals import Signal

class Form(QtWidgets.QWidget):
    def __init__(self) -> None:
        super().__init__()
        self.setupUi()
        self.signal = Signal()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(430, 570)
        self.setMinimumSize(QtCore.QSize(430, 570))
        self.setMaximumSize(QtCore.QSize(430, 570))
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self)
        self.label.setMinimumSize(QtCore.QSize(410, 40))
        self.label.setMaximumSize(QtCore.QSize(410, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(80, 83, 255);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem)
        self.label_2 = QtWidgets.QLabel(parent=self)
        self.label_2.setMinimumSize(QtCore.QSize(200, 15))
        self.label_2.setMaximumSize(QtCore.QSize(200, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self)
        self.label_3.setMinimumSize(QtCore.QSize(200, 15))
        self.label_3.setMaximumSize(QtCore.QSize(200, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(parent=self)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius: 15px;")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-radius: 15px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem1)
        self.label_4 = QtWidgets.QLabel(parent=self)
        self.label_4.setMinimumSize(QtCore.QSize(400, 30))
        self.label_4.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(405, 30))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(400, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border-radius: 15px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.lineEdit_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem2)
        self.label_5 = QtWidgets.QLabel(parent=self)
        self.label_5.setMinimumSize(QtCore.QSize(200, 20))
        self.label_5.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self)
        self.label_6.setMinimumSize(QtCore.QSize(200, 20))
        self.label_6.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border-radius: 15px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lineEdit_4)
        self.comboBox = QtWidgets.QComboBox(parent=self)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem3)
        self.label_7 = QtWidgets.QLabel(parent=self)
        self.label_7.setMinimumSize(QtCore.QSize(200, 20))
        self.label_7.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self)
        self.label_8.setMinimumSize(QtCore.QSize(200, 20))
        self.label_8.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_8)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(100, 30))
        self.lineEdit_5.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("border-radius: 15px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("border-radius: 15px;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.formLayout.setItem(13, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem4)
        self.label_9 = QtWidgets.QLabel(parent=self)
        self.label_9.setMinimumSize(QtCore.QSize(400, 20))
        self.label_9.setMaximumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_9)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(405, 30))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(405, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("border-radius: 15px;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.lineEdit_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.pushButton = QtWidgets.QPushButton(parent=self)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(56, 59, 255);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.formLayout.setLayout(17, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.horizontalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.formLayout.setItem(16, QtWidgets.QFormLayout.ItemRole.LabelRole, spacerItem7)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)

        QtCore.QMetaObject.connectSlotsByName(self)

        self.setWindowTitle("Form")
        self.label.setText("Shipping form")
        self.label_2.setText("First Name *")
        self.label_3.setText("Last Name *")
        self.label_4.setText("Street Address *")
        self.label_5.setText("City *")
        self.label_6.setText("Region *")
        self.comboBox.setItemText(0, "Andijon")
        self.comboBox.setItemText(1, "Farg\'ona")
        self.comboBox.setItemText(2, "Namangan")
        self.comboBox.setItemText(3, "Toshkent")
        self.comboBox.setItemText(4, "Jizzax")
        self.comboBox.setItemText(5, "Sirdaryo")
        self.comboBox.setItemText(6, "Qashqadaryo")
        self.comboBox.setItemText(7, "Surxondaryo")
        self.comboBox.setItemText(8, "Buxoro")
        self.comboBox.setItemText(9, "Navoiy")
        self.comboBox.setItemText(10,"Samarqand")
        self.comboBox.setItemText(11,"Xorazm")
        self.comboBox.setItemText(12, "Qoraqalpog\'iston")
        self.label_7.setText("ZIP Code *")
        self.label_8.setText("Phone Number *")
        self.label_9.setText("Email Address *")
        self.pushButton.setText("Submit")
        self.pushButton.clicked.connect(self.submit)

    def submit(self):
        self.message = QtWidgets.QMessageBox.critical(self, "Error", "Ma\'lumotlaringiz yozib olingan bo\'lardi.\nAfsuski Bu knopka hozircha realizatsiya qilinmagan")
        self.lineEdit.clear()
        self.lineEdit_2.clear()
        self.lineEdit_3.clear()
        self.lineEdit_4.clear()
        self.lineEdit_5.clear()
        self.lineEdit_6.clear()
        self.lineEdit_7.clear()
        self.comboBox.setCurrentIndex(0)
        self.signal.main.emit()
        self.close()

