from PyQt6 import QtCore, QtGui, QtWidgets


class MainWindow(QtWidgets.QMainWindow):
        def __init__(self) -> None:
               super().__init__()
               self.setupUi()

        def setupUi(self):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(657, 515)
                MainWindow.setMinimumSize(QtCore.QSize(657, 515))
                MainWindow.setMaximumSize(QtCore.QSize(657, 515))
                self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.frame = QtWidgets.QFrame(parent=self.centralwidget)
                self.frame.setGeometry(QtCore.QRect(0, 0, 661, 501))
                self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
                self.frame.setObjectName("frame")
                self.category_list = QtWidgets.QListWidget(parent=self.frame)
                self.category_list.setGeometry(QtCore.QRect(20, 120, 221, 141))
                self.category_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.category_list.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
                self.category_list.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
                self.category_list.setObjectName("category_list")
                item = QtWidgets.QListWidgetItem()
                self.category_list.addItem(item)
                item = QtWidgets.QListWidgetItem()
                self.category_list.addItem(item)
                item = QtWidgets.QListWidgetItem()
                self.category_list.addItem(item)
                item = QtWidgets.QListWidgetItem()
                self.category_list.addItem(item)
                item = QtWidgets.QListWidgetItem()
                self.category_list.addItem(item)
                item = QtWidgets.QListWidgetItem()
                self.category_list.addItem(item)
                self.logo = QtWidgets.QLabel(parent=self.frame)
                self.logo.setGeometry(QtCore.QRect(20, 20, 111, 31))
                self.logo.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";\n"
        "color: rgb(255, 0, 0);")
                self.logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
                self.logo.setObjectName("logo")
                self.category_label = QtWidgets.QLabel(parent=self.frame)
                self.category_label.setGeometry(QtCore.QRect(20, 70, 111, 31))
                self.category_label.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
                self.category_label.setObjectName("category_label")
                self.search_field = QtWidgets.QLineEdit(parent=self.frame)
                self.search_field.setGeometry(QtCore.QRect(160, 20, 311, 31))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.search_field.setFont(font)
                self.search_field.setStyleSheet("border-radius: 15px;\n"
        "border: 1px solid black;")
                self.search_field.setCursorPosition(0)
                self.search_field.setObjectName("search_field")
                self.Cart_logo = QtWidgets.QLabel(parent=self.frame)
                self.Cart_logo.setGeometry(QtCore.QRect(590, 20, 31, 31))
                self.Cart_logo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.Cart_logo.setText("")
                self.Cart_logo.setPixmap(QtGui.QPixmap("img/shopping-cart.png"))
                self.Cart_logo.setScaledContents(True)
                self.Cart_logo.setObjectName("Cart_logo")
                self.user_logo = QtWidgets.QLabel(parent=self.frame)
                self.user_logo.setGeometry(QtCore.QRect(530, 20, 31, 31))
                self.user_logo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.user_logo.setText("")
                self.user_logo.setPixmap(QtGui.QPixmap("img/user.png"))
                self.user_logo.setScaledContents(True)
                self.user_logo.setObjectName("user_logo")
                self.cart_label = QtWidgets.QLabel(parent=self.frame)
                self.cart_label.setGeometry(QtCore.QRect(594, 50, 41, 16))
                self.cart_label.setObjectName("cart_label")
                self.username_label = QtWidgets.QLabel(parent=self.frame)
                self.username_label.setGeometry(QtCore.QRect(510, 50, 71, 16))
                self.username_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
                self.username_label.setObjectName("username_label")
                self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame)
                self.stackedWidget.setGeometry(QtCore.QRect(250, 80, 391, 311))
                self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.stackedWidget.setObjectName("stackedWidget")
                self.page_2 = QtWidgets.QWidget()
                self.page_2.setObjectName("page_2")
                self.stackedWidget.addWidget(self.page_2)
                self.page_3 = QtWidgets.QWidget()
                self.page_3.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.page_3.setObjectName("page_3")
                self.image = QtWidgets.QLabel(parent=self.page_3)
                self.image.setGeometry(QtCore.QRect(0, 80, 200, 200))
                self.image.setAutoFillBackground(False)
                self.image.setText("")
                self.image.setTextFormat(QtCore.Qt.TextFormat.AutoText)
                self.image.setPixmap(QtGui.QPixmap("img/watch1.jpg"))
                self.image.setScaledContents(True)
                self.image.setWordWrap(False)
                self.image.setOpenExternalLinks(False)
                self.image.setObjectName("image")
                self.price = QtWidgets.QLabel(parent=self.page_3)
                self.price.setGeometry(QtCore.QRect(230, 80, 141, 41))
                self.price.setStyleSheet("font: 500 16pt \"MS Shell Dlg 2\";\n"
        "color: rgb(0, 0, 0);")
                self.price.setObjectName("price")
                self.label_9 = QtWidgets.QLabel(parent=self.page_3)
                self.label_9.setGeometry(QtCore.QRect(230, 120, 141, 16))
                self.label_9.setStyleSheet("color: rgb(0, 170, 0);")
                self.label_9.setObjectName("label_9")
                self.deliverydate = QtWidgets.QLabel(parent=self.page_3)
                self.deliverydate.setGeometry(QtCore.QRect(230, 150, 161, 30))
                font = QtGui.QFont()
                font.setPointSize(8)
                self.deliverydate.setFont(font)
                self.deliverydate.setObjectName("deliverydate")
                self.addToCartBtn = QtWidgets.QPushButton(parent=self.page_3)
                self.addToCartBtn.setGeometry(QtCore.QRect(230, 190, 110, 35))
                self.addToCartBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.addToCartBtn.setStyleSheet("background-color: rgb(34,34,34);\n"
        "color: rgb(255, 255, 255);\n"
        "font: 600 10pt \"MS Shell Dlg 2\";\n"
        "border-radius: 16px;")
                self.addToCartBtn.setObjectName("addToCartBtn")
                self.butNowBtn = QtWidgets.QPushButton(parent=self.page_3)
                self.butNowBtn.setGeometry(QtCore.QRect(230, 240, 110, 35))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setPointSize(10)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.butNowBtn.setFont(font)
                self.butNowBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.butNowBtn.setStyleSheet("background-color: rgb(204,41,10);\n"
        "color: rgb(255, 255, 255);\n"
        "font: 600 10pt \"MS Shell Dlg 2\";\n"
        "border-radius: 16px;")
                self.butNowBtn.setObjectName("butNowBtn")
                self.likeLabel = QtWidgets.QLabel(parent=self.page_3)
                self.likeLabel.setGeometry(QtCore.QRect(350, 220, 30, 30))
                self.likeLabel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
                self.likeLabel.setText("")
                self.likeLabel.setPixmap(QtGui.QPixmap("img/heart-epmty.png"))
                self.likeLabel.setScaledContents(True)
                self.likeLabel.setObjectName("likeLabel")
                self.description = QtWidgets.QLabel(parent=self.page_3)
                self.description.setGeometry(QtCore.QRect(10, 10, 341, 51))
                self.description.setStyleSheet("font: 200 14pt \"MS Shell Dlg 2\";")
                self.description.setObjectName("description")
                self.stackedWidget.addWidget(self.page_3)
                MainWindow.setCentralWidget(self.centralwidget)

                self.retranslateUi(MainWindow)
                self.stackedWidget.setCurrentIndex(1)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                __sortingEnabled = self.category_list.isSortingEnabled()
                self.category_list.setSortingEnabled(False)
                item = self.category_list.item(0)
                item.setText(_translate("MainWindow", "Products"))
                item = self.category_list.item(1)
                item.setText(_translate("MainWindow", "Computers and Office"))
                item = self.category_list.item(2)
                item.setText(_translate("MainWindow", "Electronics"))
                item = self.category_list.item(3)
                item.setText(_translate("MainWindow", "Mobile phone and accessories"))
                item = self.category_list.item(4)
                item.setText(_translate("MainWindow", "Watch"))
                item = self.category_list.item(5)
                item.setText(_translate("MainWindow", "Shoes"))
                self.category_list.setSortingEnabled(__sortingEnabled)
                self.logo.setText(_translate("MainWindow", "AliExpress"))
                self.category_label.setText(_translate("MainWindow", "Categories>"))
                self.search_field.setPlaceholderText(_translate("MainWindow", " I\'m looking for..."))
                self.cart_label.setText(_translate("MainWindow", "Basket"))
                self.username_label.setText(_translate("MainWindow", "username"))
                self.price.setText(_translate("MainWindow", "USD 12.20"))
                self.label_9.setText(_translate("MainWindow", "There is free shipping"))
                self.deliverydate.setText(_translate("MainWindow", "Delivery by Mail dd month - Free"))
                self.addToCartBtn.setText(_translate("MainWindow", "Add to Cart"))
                self.butNowBtn.setText(_translate("MainWindow", "Buy now"))
                self.description.setText(_translate("MainWindow", "description"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
